version: '3.8'
services:
  my-jenkins:
    build: .
    user: root
    ports:
      - "8080:8080"
      - "50000:50000"
    volumes:
      - /var/jenkins/.env:/var/jenkins/.env
      - /var/run/docker.sock:/var/run/docker.sock
      - jenkins_home:/var/jenkins_home
      - /home/ec2-user/.npm:/var/jenkins_home/.npm
    mem_limit: 2.5G

volumes:
  jenkins_home:
