version: '3.8'
services:
  my-jenkins:
    network_mode: "host"
    build: .
    user: root
    ports:
      - "8080:8080"
      - "50000:50000"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - jenkins_home:/var/jenkins_home
    mem_limit: 600M
    cpus: 0.7

volumes:
  jenkins_home:
