version: '3.8'
services:
  my-jenkins-image:
    build: .

  jenkins:
    image: my-jenkins-image
    user: root
    ports:
      - "8080:8080"
      - "50000:50000"
    volumes:
      - /home/ec2-user/.npm:/tmp/npm-cache
      - /var/run/docker.sock:/var/run/docker.sock
      - /usr/bin/docker:/usr/bin/docker
      - jenkins_home:/var/jenkins_home
    mem_limit: 600M
    cpus: 0.7
    depends_on:
      - my-jenkins-image
      
volumes:
  jenkins_home: